# CloudUnflare Enhanced v2.0 - Portainer Stack Template
# Optimized for Portainer deployment with comprehensive configuration options

version: '3.8'

services:
  # Main CloudUnflare Enhanced application
  cloudunflare-main:
    image: cloudunflare-enhanced:2.0
    container_name: "${CONTAINER_NAME_PREFIX:-cloudunflare}-main"
    hostname: "${CONTAINER_NAME_PREFIX:-cloudunflare}-main"
    restart: unless-stopped

    # Build configuration (if building from source)
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        BUILD_VERSION: "${BUILD_VERSION:-2.0-Enhanced}"
        BUILD_DATE: "${BUILD_DATE}"
        BUILD_VARIANT: "standard"

    # Network configuration
    networks:
      - cloudunflare-network
      - monitoring-network

    # DNS configuration for optimal DNS operations
    dns:
      - "${PRIMARY_DNS_1:-1.1.1.1}"
      - "${PRIMARY_DNS_2:-8.8.8.8}"
      - "${SECONDARY_DNS_1:-9.9.9.9}"
      - "${SECONDARY_DNS_2:-208.67.222.222}"

    # Security configuration
    security_opt:
      - no-new-privileges:true
      - "${APPARMOR_PROFILE:-apparmor:unconfined}"

    # Capabilities for OPSEC operations
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_PTRACE

    # Resource limits
    deploy:
      resources:
        limits:
          memory: "${MAIN_MEMORY_LIMIT:-512M}"
          cpus: "${MAIN_CPU_LIMIT:-2.0}"
        reservations:
          memory: "${MAIN_MEMORY_RESERVATION:-256M}"
          cpus: "${MAIN_CPU_RESERVATION:-1.0}"

    # Volume mounts
    volumes:
      - type: bind
        source: "${CLOUDUNFLARE_CONFIG_PATH:-./data/config}"
        target: /app/config
        read_only: true
      - type: bind
        source: "${CLOUDUNFLARE_RESULTS_PATH:-./data/results}"
        target: /app/results
      - type: bind
        source: "${CLOUDUNFLARE_LOGS_PATH:-./data/logs}"
        target: /app/logs
      - type: bind
        source: "${CLOUDUNFLARE_WORDLISTS_PATH:-./data/wordlists}"
        target: /app/wordlists
        read_only: true
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M
          mode: 1777

    # Environment variables
    environment:
      # Application configuration
      - CLOUDUNFLARE_MAX_THREADS=${CLOUDUNFLARE_MAX_THREADS:-50}
      - CLOUDUNFLARE_DNS_TIMEOUT=${CLOUDUNFLARE_DNS_TIMEOUT:-30}
      - CLOUDUNFLARE_HTTP_TIMEOUT=${CLOUDUNFLARE_HTTP_TIMEOUT:-45}
      - CLOUDUNFLARE_OPSEC_MODE=${CLOUDUNFLARE_OPSEC_MODE:-1}
      - CLOUDUNFLARE_LOG_LEVEL=${CLOUDUNFLARE_LOG_LEVEL:-1}
      - CLOUDUNFLARE_PERFORMANCE_MODE=${CLOUDUNFLARE_PERFORMANCE_MODE:-1}

      # Advanced DNS settings
      - CLOUDUNFLARE_DOH_ENABLED=${CLOUDUNFLARE_DOH_ENABLED:-1}
      - CLOUDUNFLARE_DOQ_ENABLED=${CLOUDUNFLARE_DOQ_ENABLED:-1}
      - CLOUDUNFLARE_DOT_ENABLED=${CLOUDUNFLARE_DOT_ENABLED:-1}
      - CLOUDUNFLARE_IPV6_ENABLED=${CLOUDUNFLARE_IPV6_ENABLED:-1}

      # Security settings
      - CLOUDUNFLARE_STEALTH_MODE=${CLOUDUNFLARE_STEALTH_MODE:-1}
      - CLOUDUNFLARE_USER_AGENT_ROTATION=${CLOUDUNFLARE_USER_AGENT_ROTATION:-1}
      - CLOUDUNFLARE_RATE_LIMITING=${CLOUDUNFLARE_RATE_LIMITING:-1}

      # Paths
      - CLOUDUNFLARE_CONFIG_PATH=/app/config
      - CLOUDUNFLARE_RESULTS_PATH=/app/results
      - CLOUDUNFLARE_LOGS_PATH=/app/logs
      - CLOUDUNFLARE_WORDLISTS_PATH=/app/wordlists

      # System
      - TZ=${TZ:-UTC}

    # Health monitoring
    healthcheck:
      test: ["/app/healthcheck.sh"]
      interval: "${HEALTHCHECK_INTERVAL:-30s}"
      timeout: "${HEALTHCHECK_TIMEOUT:-10s}"
      retries: "${HEALTHCHECK_RETRIES:-3}"
      start_period: "${HEALTHCHECK_START_PERIOD:-10s}"

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-10m}"
        max-file: "${LOG_MAX_FILES:-3}"

    # Labels for Portainer management
    labels:
      - "traefik.enable=false"
      - "cloudunflare.service=main"
      - "cloudunflare.version=${BUILD_VERSION:-2.0-enhanced}"
      - "portainer.stack.name=${PORTAINER_STACK_NAME:-cloudunflare}"
      - "cloudunflare.description=Main DNS reconnaissance application"

  # Reconnaissance variant (optional - enabled via environment variable)
  cloudunflare-recon:
    image: cloudunflare-enhanced:2.0-recon
    container_name: "${CONTAINER_NAME_PREFIX:-cloudunflare}-recon"
    hostname: "${CONTAINER_NAME_PREFIX:-cloudunflare}-recon"
    restart: unless-stopped
    profiles:
      - recon

    # Build configuration for reconnaissance variant
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        BUILD_VERSION: "${BUILD_VERSION:-2.0-Enhanced-Recon}"
        BUILD_DATE: "${BUILD_DATE}"
        BUILD_VARIANT: "reconnaissance"

    networks:
      - cloudunflare-network
      - monitoring-network

    dns:
      - "${PRIMARY_DNS_1:-1.1.1.1}"
      - "${PRIMARY_DNS_2:-8.8.8.8}"

    security_opt:
      - no-new-privileges:true
      - "${APPARMOR_PROFILE:-apparmor:unconfined}"

    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_PTRACE
      - SYS_ADMIN

    deploy:
      resources:
        limits:
          memory: "${RECON_MEMORY_LIMIT:-1G}"
          cpus: "${RECON_CPU_LIMIT:-4.0}"
        reservations:
          memory: "${RECON_MEMORY_RESERVATION:-512M}"
          cpus: "${RECON_CPU_RESERVATION:-2.0}"

    volumes:
      - type: bind
        source: "${CLOUDUNFLARE_CONFIG_PATH:-./data/config}"
        target: /app/config
        read_only: true
      - type: bind
        source: "${CLOUDUNFLARE_RECON_RESULTS_PATH:-./data/recon-results}"
        target: /app/results
      - type: bind
        source: "${CLOUDUNFLARE_LOGS_PATH:-./data/logs}"
        target: /app/logs
      - type: bind
        source: "${CLOUDUNFLARE_WORDLISTS_PATH:-./data/wordlists}"
        target: /app/wordlists
        read_only: true
      - type: bind
        source: "${CLOUDUNFLARE_PROBES_PATH:-./data/probes}"
        target: /app/probes
        read_only: true

    environment:
      # Enhanced settings for reconnaissance
      - CLOUDUNFLARE_MAX_THREADS=${RECON_MAX_THREADS:-100}
      - CLOUDUNFLARE_DNS_TIMEOUT=${RECON_DNS_TIMEOUT:-60}
      - CLOUDUNFLARE_OPSEC_MODE=${CLOUDUNFLARE_OPSEC_MODE:-1}
      - CLOUDUNFLARE_LOG_LEVEL=${RECON_LOG_LEVEL:-2}
      - CLOUDUNFLARE_RECON_MODE=1
      - RECON_MODULES_ENABLED=1

      # Reconnaissance module settings
      - RECON_DNS_ZONE_TRANSFER=${RECON_DNS_ZONE_TRANSFER:-0}
      - RECON_DNS_BRUTEFORCE=${RECON_DNS_BRUTEFORCE:-0}
      - RECON_HTTP_BANNER_GRABBING=${RECON_HTTP_BANNER_GRABBING:-0}
      - RECON_PORT_SCANNING=${RECON_PORT_SCANNING:-0}
      - RECON_MAX_CONCURRENT=${RECON_MAX_CONCURRENT:-50}

      # OPSEC settings for reconnaissance
      - RECON_STEALTH_DELAY_MS=${RECON_STEALTH_DELAY_MS:-1000}

      - TZ=${TZ:-UTC}

    command: ["/app/cloudunflare-recon"]

    healthcheck:
      test: ["/app/healthcheck.sh"]
      interval: "45s"
      timeout: "15s"
      retries: 3
      start_period: "15s"

    labels:
      - "cloudunflare.service=reconnaissance"
      - "cloudunflare.version=${BUILD_VERSION:-2.0-enhanced-recon}"
      - "portainer.stack.name=${PORTAINER_STACK_NAME:-cloudunflare}"
      - "cloudunflare.description=Advanced reconnaissance modules"

  # Monitoring service (optional - enabled via profile)
  cloudunflare-monitor:
    image: prom/node-exporter:latest
    container_name: "${CONTAINER_NAME_PREFIX:-cloudunflare}-monitor"
    hostname: "${CONTAINER_NAME_PREFIX:-cloudunflare}-monitor"
    restart: unless-stopped
    profiles:
      - monitoring

    networks:
      - monitoring-network

    ports:
      - "${MONITOR_PORT:-9100}:9100"

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

    labels:
      - "cloudunflare.service=monitoring"
      - "portainer.stack.name=${PORTAINER_STACK_NAME:-cloudunflare}"
      - "cloudunflare.description=System metrics collection"

  # Log aggregation service (optional - enabled via profile)
  cloudunflare-logs:
    image: fluent/fluent-bit:latest
    container_name: "${CONTAINER_NAME_PREFIX:-cloudunflare}-logs"
    hostname: "${CONTAINER_NAME_PREFIX:-cloudunflare}-logs"
    restart: unless-stopped
    profiles:
      - logging

    networks:
      - monitoring-network

    volumes:
      - type: bind
        source: "${CLOUDUNFLARE_LOGS_PATH:-./data/logs}"
        target: /fluent-bit/log
        read_only: true
      - type: bind
        source: "./fluent-bit.conf"
        target: /fluent-bit/etc/fluent-bit.conf
        read_only: true
      - type: bind
        source: "./parsers.conf"
        target: /fluent-bit/etc/parsers.conf
        read_only: true

    depends_on:
      - cloudunflare-main

    labels:
      - "cloudunflare.service=logging"
      - "portainer.stack.name=${PORTAINER_STACK_NAME:-cloudunflare}"
      - "cloudunflare.description=Log aggregation and processing"

# Network configuration
networks:
  cloudunflare-network:
    driver: bridge
    ipam:
      config:
        - subnet: "${CLOUDUNFLARE_NETWORK_SUBNET:-172.20.0.0/16}"
          gateway: "${CLOUDUNFLARE_NETWORK_GATEWAY:-172.20.0.1}"
    driver_opts:
      com.docker.network.bridge.name: cloudunflare-br
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"
    labels:
      - "cloudunflare.network=main"
      - "cloudunflare.purpose=dns-reconnaissance"

  monitoring-network:
    driver: bridge
    ipam:
      config:
        - subnet: "${MONITORING_NETWORK_SUBNET:-172.21.0.0/16}"
          gateway: "${MONITORING_NETWORK_GATEWAY:-172.21.0.1}"
    labels:
      - "cloudunflare.network=monitoring"
      - "cloudunflare.purpose=observability"

# Portainer template configuration
x-portainer-templates:
  cloudunflare-enhanced:
    title: "CloudUnflare Enhanced v2.0"
    description: "High-performance DNS reconnaissance tool with OPSEC capabilities"
    note: "Deploys CloudUnflare Enhanced with optional reconnaissance and monitoring modules"

    categories:
      - security
      - networking
      - reconnaissance

    platform: linux

    logo: "https://raw.githubusercontent.com/portainer/templates/master/Images/registry.png"

    repository:
      url: "https://github.com/user/cloudunflare-enhanced"
      stackfile: "portainer-stack.yml"

    env:
      # Basic Configuration
      - name: "BUILD_VERSION"
        label: "Build Version"
        description: "CloudUnflare Enhanced version"
        default: "2.0-Enhanced"

      - name: "CLOUDUNFLARE_MAX_THREADS"
        label: "Max Threads"
        description: "Maximum number of concurrent threads (1-100)"
        default: "50"

      - name: "CLOUDUNFLARE_DNS_TIMEOUT"
        label: "DNS Timeout"
        description: "DNS query timeout in seconds (5-120)"
        default: "30"

      - name: "CLOUDUNFLARE_OPSEC_MODE"
        label: "OPSEC Mode"
        description: "Enable OPSEC protections (0=disabled, 1=enabled)"
        default: "1"
        select:
          - text: "Disabled"
            value: "0"
          - text: "Enabled"
            value: "1"
            default: true

      - name: "CLOUDUNFLARE_LOG_LEVEL"
        label: "Log Level"
        description: "Logging verbosity"
        default: "1"
        select:
          - text: "Silent"
            value: "0"
          - text: "Normal"
            value: "1"
            default: true
          - text: "Verbose"
            value: "2"
          - text: "Debug"
            value: "3"

      # Advanced DNS Configuration
      - name: "CLOUDUNFLARE_DOH_ENABLED"
        label: "DNS-over-HTTPS"
        description: "Enable DNS-over-HTTPS support"
        default: "1"
        select:
          - text: "Disabled"
            value: "0"
          - text: "Enabled"
            value: "1"
            default: true

      - name: "CLOUDUNFLARE_IPV6_ENABLED"
        label: "IPv6 Support"
        description: "Enable IPv6 DNS resolution"
        default: "1"
        select:
          - text: "Disabled"
            value: "0"
          - text: "Enabled"
            value: "1"
            default: true

      # Resource Configuration
      - name: "MAIN_MEMORY_LIMIT"
        label: "Memory Limit (Main)"
        description: "Memory limit for main container"
        default: "512M"

      - name: "MAIN_CPU_LIMIT"
        label: "CPU Limit (Main)"
        description: "CPU limit for main container"
        default: "2.0"

      # Volume Paths
      - name: "CLOUDUNFLARE_CONFIG_PATH"
        label: "Configuration Path"
        description: "Path to configuration directory"
        default: "./data/config"

      - name: "CLOUDUNFLARE_RESULTS_PATH"
        label: "Results Path"
        description: "Path to results output directory"
        default: "./data/results"

      - name: "CLOUDUNFLARE_WORDLISTS_PATH"
        label: "Wordlists Path"
        description: "Path to wordlists directory"
        default: "./data/wordlists"

      # Network Configuration
      - name: "PRIMARY_DNS_1"
        label: "Primary DNS Server 1"
        description: "First primary DNS server"
        default: "1.1.1.1"

      - name: "PRIMARY_DNS_2"
        label: "Primary DNS Server 2"
        description: "Second primary DNS server"
        default: "8.8.8.8"